"use client";

export default function HandoverPage() {
  return (
    <div className="max-w-4xl space-y-6">
      <h1 className="text-xl font-bold" style={{ color: "var(--text-primary)" }}>개발 인수인계 문서</h1>
      <p className="text-[12px]" style={{ color: "var(--text-secondary)" }}>최종 업데이트: 2026-04-07</p>

      <Section title="1. 프로젝트 개요">
        <P>라이브Felix (livefelix.com) — 스포츠 중계/분석/커뮤니티 플랫폼</P>
        <UL items={[
          "실시간 스포츠 중계 릴레이 + BJ 라이브 방송",
          "AI 스포츠 분석 (자동/수동)",
          "실시간 채팅 (Socket.IO)",
          "출석체크, 포인트/레벨 시스템, 이벤트 매치",
          "팀 로고 자동 수집 + WebP 최적화",
          "SEO 관리, 관리자 대시보드",
        ]} />
      </Section>

      <Section title="2. 기술 스택">
        <Table headers={["영역", "기술", "비고"]} rows={[
          ["프레임워크", "Next.js 14 App Router", "커스텀 서버(server.js)"],
          ["DB", "PostgreSQL + Prisma ORM", "싱글톤 /lib/prisma.ts"],
          ["실시간", "Socket.IO", "메인 채팅 + BJ 채팅 모두"],
          ["미디어 서버", "SRS (RTMP → HLS/FLV)", "mpegts.js 저지연 플레이어"],
          ["리버스 프록시", "nginx + Cloudflare", "WebP 자동 변환 포함"],
          ["AI", "Claude / GPT-4o-mini / Gemini 2.0 Flash", "관리자 설정에서 API 키 관리"],
          ["외부 API", "ESPN, livescore.co.kr, winner-stream, TheSportsDB, YouTube", ""],
          ["인증", "JWT (쿠키 기반)", "livetv_token 쿠키"],
        ]} />
      </Section>

      <Section title="3. 핵심 아키텍처">
        <SubSection title="3-1. 서버 구조">
        <Code>{`server.js (커스텀 Next.js 서버)
├── HTTP Server (port 3000)
├── Socket.IO
│   ├── 메인 공개 채팅 (chat:send, chat:delete, chat:pin)
│   └── BJ 개별 채팅 (bj:join, bj:send, bj:delete, bj:pin) ← room 기반
├── node-cron (자동 분석 스케줄러)
└── Next.js App (SSR + API Routes)

실행: NODE_ENV=production node server.js
포트 충돌 시: kill -9 $(lsof -ti:3000)`}</Code>
        </SubSection>

        <SubSection title="3-2. DB 주요 모델">
        <Code>{`User — 회원 (role: USER/PICKSTER/BJ/ADMIN/SUPERADMIN/DEVELOPER)
ChatMessage — 메인 채팅 (level, isPinned)
BjProfile — BJ 프로필 (avatar, banner, pinnedMessage, liveStartedAt, liveViewers)
BjChatMessage — BJ 개별 채팅 (isPinned)
BjChatBan / BjChatManager — 차단/매니저
BjViewLog — IP 기반 시청자 추적 (heartbeat 30초)
TeamLogo — 팀 로고 (nameKr unique, nameEn, logoPath)
AnalysisPost — 분석글 (isAutoGenerated, matchKey, isDraft)
AutoAnalysisSetting — 자동 분석 설정
Event / EventVote — 이벤트 매치
Attendance — 출석체크 (@db.Date, KST 기준)
SiteSetting — 사이트 전체 설정 (SEO, 로고 토글, API 키, 한줄공지)
AdminLog — 관리자 감사 로그
LevelSetting — 레벨 구간 설정
ActivityReward — 활동 보상 설정`}</Code>
        </SubSection>

        <SubSection title="3-3. 날짜 처리 (중요!)">
        <P>서버 시간대: UTC. 한국시간 기준 처리를 위해 lib/date-kr.ts 사용.</P>
        <Code>{`todayDateKST() — @db.Date 컬럼용 (출석체크 등)
todayKST()     — DateTime 컬럼 범위 쿼리용 (createdAt >= todayKST())
startOfMonthKST() / endOfMonthKST() — 월별 조회용

주의: new Date(); setHours(0,0,0,0) 절대 사용 금지 (UTC 자정 = KST 오전 9시)`}</Code>
        </SubSection>
      </Section>

      <Section title="4. 주요 기능별 파일 맵">
        <SubSection title="4-1. 스포츠 중계">
        <Code>{`app/broadcast/ — 중계 페이지
app/api/sports-live/route.ts — winner-stream.com에서 중계 목록
lib/sports-live.ts — 데이터 파싱
app/api/broadcast-player/route.ts — HLS 플레이어 HTML
app/api/stream/route.ts — 스트림 프록시 (CORS 우회)`}</Code>
        </SubSection>

        <SubSection title="4-2. BJ 라이브 방송">
        <Code>{`app/live/page.tsx — 라이브 페이지 (플레이어 + 채팅)
app/bj/dashboard/page.tsx — BJ 대시보드
app/api/bj/ — BJ API (all, me, chat, avatar, chat/ban, chat/manager, chat/pin, chat/settings)
app/api/stream/auth/route.ts — SRS 콜백 (on_publish/on_unpublish)
server.js — Socket.IO bj:* 이벤트

시청자 추적: app/api/bj/[streamKey]/route.ts (IP heartbeat 30초)
방송 시작 시: viewCount/viewLog 초기화, liveStartedAt 설정`}</Code>
        </SubSection>

        <SubSection title="4-3. 팀 로고 시스템">
        <Code>{`DB: TeamLogo (nameKr unique)
API: /api/team-logos — 한글/영문/공백변형 키 모두 반환
매칭: 정확매칭 → 부분매칭 → 공백제거/추가 변형

파일: /public/team-logos/ (PNG 원본 + WebP 변환)
nginx: Accept: webp 감지 → .webp 자동 서빙
캐시 버스팅: ?v=3 쿼리스트링

로고 추가 프로세스:
1. TheSportsDB / Wikipedia에서 다운로드
2. cwebp -q 90 변환
3. DB upsert (nameKr, nameEn, logoPath)

주의: nameKr unique 제약 → 동명 다종목팀 등록 불가
향후 충돌 시 @@unique([nameKr, sport]) 복합키로 변경 필요`}</Code>
        </SubSection>

        <SubSection title="4-4. AI 자동 분석">
        <Code>{`lib/auto-analysis.ts — 핵심 로직
  1. /api/standings에서 상위 N위 팀 추출 (한글 전적)
  2. ESPN Schedule에서 해당 팀 다음 경기 필터링
  3. TeamLogo DB로 영문→한글 팀명/로고 변환
  4. AI 호출 (Claude/GPT/Gemini)
  5. AnalysisPost DB 저장

app/api/admin/auto-analysis/ — 설정 CRUD + 수동 실행
app/api/admin/auto-analysis/publish/ — 일괄 게시/삭제
server.js — node-cron 스케줄러 (KST→UTC 변환)
게시 계정: auto_pickster (닉네임: 픽스터)`}</Code>
        </SubSection>

        <SubSection title="4-5. SEO">
        <Code>{`app/layout.tsx — generateMetadata() 동적 메타태그 + GA4 + JSON-LD
app/sitemap.ts — 동적 사이트맵 (정적+분석글+이벤트+공지)
app/robots.ts — DB 기반 robots.txt
app/api/admin/seo/route.ts — SEO 설정 API
components/ui/MetaHead.tsx — 클라이언트 페이지 동적 메타태그
components/ui/JsonLd.tsx — 구조화 데이터 컴포넌트`}</Code>
        </SubSection>

        <SubSection title="4-6. 채팅 시스템">
        <Code>{`메인 채팅: Socket.IO 실시간 (server.js chat:* 이벤트)
  - components/layout/RightSidebar.tsx (데스크탑)
  - components/layout/FloatingPanel.tsx (모바일)

BJ 채팅: Socket.IO room 기반 (server.js bj:* 이벤트)
  - app/live/page.tsx
  - 기능: 배너, 고정메시지, 시스템메시지, PIN, 삭제/차단/매니저

REST API 폴백: /api/chat, /api/bj/chat (Socket 실패 시)`}</Code>
        </SubSection>
      </Section>

      <Section title="5. nginx 설정">
        <Code>{`파일: /etc/nginx/sites-enabled/livefelix.com

핵심 location:
/team-logos/ — 정적 서빙 + WebP 자동 전환 (7일 캐시)
/uploads/ — 업로드 이미지 서빙 (1일 캐시)
/live/*.m3u8|ts|flv — SRS 프록시 (:8080)
/ — Next.js 프록시 (:3000, WebSocket 업그레이드 포함)

주의: client_max_body_size 10M (두 server 블록 모두)`}</Code>
      </Section>

      <Section title="6. 환경 변수">
        <Code>{`NODE_ENV=production
JWT_SECRET (기본값 있음, 변경 권장)
ANTHROPIC_API_KEY (환경변수 또는 SiteSetting DB)
DATABASE_URL (Prisma)
SRS: /root/srs.conf (RTMP :1935, HTTP :8080)`}</Code>
      </Section>

      <Section title="7. 배포 절차">
        <Code>{`1. npm run build
2. kill -9 $(lsof -ti:3000)
3. NODE_ENV=production nohup node server.js > /tmp/server.log 2>&1 &
4. nginx -s reload (nginx 설정 변경 시)

DB 스키마 변경 시: npx prisma db push --accept-data-loss
Prisma 클라이언트 재생성: npx prisma generate`}</Code>
      </Section>

      <Section title="8. 알려진 제약사항">
        <UL items={[
          "TeamLogo nameKr unique 제약 → 동명 다종목팀 미지원 (현재 충돌 없음)",
          "BJ 채팅 시스템 메시지: BJ 본인 브라우저에서만 타이머 동작 (서버 cron 아님)",
          "메인 페이지 revalidate 30분 → 이벤트/하이라이트 갱신 지연 (한줄공지는 클라이언트 fetch로 즉시 반영)",
          "YouTube 하이라이트: 채널별 HTML 스크래핑 → YouTube 구조 변경 시 파싱 실패 가능",
          "리치 텍스트 에디터: react-quill-new 사용, 이미지 업로드는 /api/upload 경유",
          "자동 분석: 리그당 최대 3경기, AI 호출 간 2초 딜레이 (rate limit 방지)",
        ]} />
      </Section>

      <Section title="9. 골드 악센트">
        <P>globals.css에 클래식 골드(212,175,55) 고정 적용. 카드 테두리 + 글로우 + 스크롤바.</P>
        <P>GoldAccentPanel 컴포넌트는 주석 처리 상태 (필요 시 복원 가능).</P>
      </Section>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="rounded-lg p-4" style={{ background: "var(--surface)", border: "1px solid var(--border)" }}>
      <h2 className="text-[15px] font-bold mb-3" style={{ color: "var(--text-primary)" }}>{title}</h2>
      <div className="space-y-2">{children}</div>
    </div>
  );
}
function SubSection({ title, children }: { title: string; children: React.ReactNode }) {
  return <div className="mt-3"><h3 className="text-[13px] font-bold mb-1" style={{ color: "var(--text-primary)" }}>{title}</h3>{children}</div>;
}
function P({ children }: { children: React.ReactNode }) {
  return <p className="text-[12px] leading-relaxed" style={{ color: "var(--text-secondary)" }}>{children}</p>;
}
function UL({ items }: { items: string[] }) {
  return <ul className="list-disc ml-4 space-y-0.5">{items.map((item, i) => <li key={i} className="text-[12px]" style={{ color: "var(--text-secondary)" }}>{item}</li>)}</ul>;
}
function Code({ children }: { children: string }) {
  return <pre className="text-[11px] p-3 rounded overflow-x-auto" style={{ background: "var(--bg)", color: "var(--text-primary)", border: "1px solid var(--border)" }}>{children}</pre>;
}
function Table({ headers, rows }: { headers: string[]; rows: string[][] }) {
  return (
    <div className="overflow-x-auto">
      <table className="w-full text-[11px]" style={{ border: "1px solid var(--border)" }}>
        <thead><tr style={{ background: "var(--bg)" }}>{headers.map(h => <th key={h} className="px-2 py-1.5 text-left font-bold" style={{ color: "var(--text-secondary)", borderBottom: "1px solid var(--border)" }}>{h}</th>)}</tr></thead>
        <tbody>{rows.map((row, i) => <tr key={i} style={{ borderBottom: "1px solid var(--border)" }}>{row.map((cell, j) => <td key={j} className="px-2 py-1.5" style={{ color: "var(--text-primary)" }}>{cell}</td>)}</tr>)}</tbody>
      </table>
    </div>
  );
}
