export const dynamic = "force-dynamic";

import { prisma } from "@/lib/prisma";
import { NextRequest, NextResponse } from "next/server";
import { getSession } from "@/lib/auth";
import { adminLog } from "@/lib/admin-log";

export async function GET() {
  const session = await getSession();
  if (!session || !["ADMIN", "SUPERADMIN", "DEVELOPER"].includes(session.role)) {
    return NextResponse.json({ error: "권한 없음" }, { status: 403 });
  }

  const settings = await prisma.autoAnalysisSetting.findFirst();
  const recentPosts = await prisma.analysisPost.findMany({
    where: { isAutoGenerated: true },
    orderBy: { createdAt: "desc" },
    take: 20,
    select: { id: true, title: true, league: true, homeTeam: true, awayTeam: true, homeLogo: true, awayLogo: true, isDraft: true, matchKey: true, createdAt: true },
  });

  return NextResponse.json({ settings, recentPosts });
}

export async function PUT(req: NextRequest) {
  const session = await getSession();
  if (!session || !["ADMIN", "SUPERADMIN", "DEVELOPER"].includes(session.role)) {
    return NextResponse.json({ error: "권한 없음" }, { status: 403 });
  }

  const body = await req.json();
  const data: Record<string, unknown> = {};
  if (body.isEnabled !== undefined) data.isEnabled = body.isEnabled;
  if (body.targetLeagues !== undefined) data.targetLeagues = typeof body.targetLeagues === "string" ? body.targetLeagues : JSON.stringify(body.targetLeagues);
  if (body.topN !== undefined) data.topN = body.topN;
  if (body.cronHour !== undefined) data.cronHour = body.cronHour;
  if (body.cronMinute !== undefined) data.cronMinute = body.cronMinute;
  if (body.aiModel !== undefined) data.aiModel = body.aiModel;
  if (body.autoPublish !== undefined) data.autoPublish = body.autoPublish;

  await prisma.autoAnalysisSetting.upsert({
    where: { id: 1 },
    create: { id: 1, ...data },
    update: data,
  });

  await adminLog({ action: "auto-analysis.settings.update", detail: data });
  return NextResponse.json({ ok: true });
}

// POST: 수동 실행
export async function POST() {
  const session = await getSession();
  if (!session || !["ADMIN", "SUPERADMIN", "DEVELOPER"].includes(session.role)) {
    return NextResponse.json({ error: "권한 없음" }, { status: 403 });
  }

  try {
    // 동적 import (서버 전용 모듈)
    const { runAutoAnalysis } = await import("@/lib/auto-analysis");
    const result = await runAutoAnalysis(true);
    await adminLog({ action: "auto-analysis.manual-run", detail: result });
    return NextResponse.json(result);
  } catch (e) {
    return NextResponse.json({ error: e instanceof Error ? e.message : "실행 실패" }, { status: 500 });
  }
}
