export const dynamic = "force-dynamic";

import { prisma } from "@/lib/prisma";
import { NextRequest, NextResponse } from "next/server";
import { getSession } from "@/lib/auth";
import { adminLog } from "@/lib/admin-log";

// POST: 선택한 임시 글들을 게시
export async function POST(req: NextRequest) {
  const session = await getSession();
  if (!session || !["ADMIN", "SUPERADMIN", "DEVELOPER"].includes(session.role)) {
    return NextResponse.json({ error: "권한 없음" }, { status: 403 });
  }

  const { ids, action } = await req.json();
  if (!Array.isArray(ids) || ids.length === 0) {
    return NextResponse.json({ error: "대상이 없습니다" }, { status: 400 });
  }

  if (action === "publish") {
    await prisma.analysisPost.updateMany({
      where: { id: { in: ids }, isAutoGenerated: true },
      data: { isDraft: false, isPublic: true },
    });
    await adminLog({ action: "auto-analysis.publish", detail: { ids } });
    return NextResponse.json({ ok: true, count: ids.length });
  }

  if (action === "delete") {
    await prisma.analysisPost.deleteMany({
      where: { id: { in: ids }, isAutoGenerated: true },
    });
    await adminLog({ action: "auto-analysis.delete", detail: { ids } });
    return NextResponse.json({ ok: true, count: ids.length });
  }

  return NextResponse.json({ error: "잘못된 액션" }, { status: 400 });
}
